# Generated by Django 5.0.8 on 2024-09-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(
                default="action", help_text="type of the movie", max_length=200
            ),
        ),
    ]
