# Generated by Django 5.0.8 on 2024-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(default="default.png", upload_to="images/"),
        ),
    ]
